/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AssetApi", () => {
  let instance: api.AssetApi
  beforeEach(function() {
    instance = new api.AssetApi(config)
  });

  test("3f1618f3ab09735d63c93a014d82c4f2", () => {
    const id: number = 56
    return expect(instance.3f1618f3ab09735d63c93a014d82c4f2(id, {})).resolves.toBe(null)
  })
  test("5baf39dba56d410a1bf7eb6c1cfe6507", () => {
    const name: string = "name_example"
    return expect(instance.5baf39dba56d410a1bf7eb6c1cfe6507(name, {})).resolves.toBe(null)
  })
  test("81e573317d0ccd3a1a3bb21296048765", () => {
    const id: number = 56
    return expect(instance.81e573317d0ccd3a1a3bb21296048765(id, {})).resolves.toBe(null)
  })
  test("abe283cafa8b21156dee4a870c67a59a", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.abe283cafa8b21156dee4a870c67a59a(name, id, {})).resolves.toBe(null)
  })
  test("bf2ac34b89b5240c36742fc783b640cc", () => {
    return expect(instance.bf2ac34b89b5240c36742fc783b640cc({})).resolves.toBe(null)
  })
})

describe("CaveApi", () => {
  let instance: api.CaveApi
  beforeEach(function() {
    instance = new api.CaveApi(config)
  });

  test("14757fb12ad2e8397562b4882969690f", () => {
    return expect(instance.14757fb12ad2e8397562b4882969690f({})).resolves.toBe(null)
  })
  test("1c622d9db9c463a33aa532b32f3d23de", () => {
    const id: number = 56
    return expect(instance.1c622d9db9c463a33aa532b32f3d23de(id, {})).resolves.toBe(null)
  })
  test("577a84bf0de4130a9b10d13f0c622bf1", () => {
    const name: string = "name_example"
    return expect(instance.577a84bf0de4130a9b10d13f0c622bf1(name, {})).resolves.toBe(null)
  })
  test("704e65587b6fff0267744aa4bc2adaba", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.704e65587b6fff0267744aa4bc2adaba(name, id, {})).resolves.toBe(null)
  })
  test("ea8453b16a586fecc4057c830d319683", () => {
    const id: number = 56
    return expect(instance.ea8453b16a586fecc4057c830d319683(id, {})).resolves.toBe(null)
  })
})

describe("CaveEntranceApi", () => {
  let instance: api.CaveEntranceApi
  beforeEach(function() {
    instance = new api.CaveEntranceApi(config)
  });

  test("0b7098a3a4db3f15d66d5d173d9b70b9", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.0b7098a3a4db3f15d66d5d173d9b70b9(name, id, {})).resolves.toBe(null)
  })
  test("2681ef5be66c133e9568f713e314cff1", () => {
    const name: string = "name_example"
    return expect(instance.2681ef5be66c133e9568f713e314cff1(name, {})).resolves.toBe(null)
  })
  test("53a160ba0cab52eadcafc744884ce3b3", () => {
    const id: number = 56
    return expect(instance.53a160ba0cab52eadcafc744884ce3b3(id, {})).resolves.toBe(null)
  })
  test("632f6231938573947ef4f90a83558ae3", () => {
    return expect(instance.632f6231938573947ef4f90a83558ae3({})).resolves.toBe(null)
  })
  test("9e8ab160c3a28640fafc3953110f313e", () => {
    const id: number = 56
    return expect(instance.9e8ab160c3a28640fafc3953110f313e(id, {})).resolves.toBe(null)
  })
})

describe("CaveTypeApi", () => {
  let instance: api.CaveTypeApi
  beforeEach(function() {
    instance = new api.CaveTypeApi(config)
  });

  test("25165acbf62fa3c489e9491389b227b3", () => {
    return expect(instance.25165acbf62fa3c489e9491389b227b3({})).resolves.toBe(null)
  })
  test("32d694f9aceadd67af72aef20ac33467", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.32d694f9aceadd67af72aef20ac33467(name, id, {})).resolves.toBe(null)
  })
  test("384448f895a8883569eb386b1ee359dc", () => {
    const id: number = 56
    return expect(instance.384448f895a8883569eb386b1ee359dc(id, {})).resolves.toBe(null)
  })
  test("8aca8360affea531d604a5c03b92f24d", () => {
    const name: string = "name_example"
    return expect(instance.8aca8360affea531d604a5c03b92f24d(name, {})).resolves.toBe(null)
  })
  test("dc66aac759b9c8cb9d085b553c4a1371", () => {
    const id: number = 56
    return expect(instance.dc66aac759b9c8cb9d085b553c4a1371(id, {})).resolves.toBe(null)
  })
})

describe("EntranceTypeApi", () => {
  let instance: api.EntranceTypeApi
  beforeEach(function() {
    instance = new api.EntranceTypeApi(config)
  });

  test("0f4f2571698f671d4964dbae0cc0bb2e", () => {
    const id: number = 56
    return expect(instance.0f4f2571698f671d4964dbae0cc0bb2e(id, {})).resolves.toBe(null)
  })
  test("1d29dd792139235db6955b6b998e529c", () => {
    const name: string = "name_example"
    return expect(instance.1d29dd792139235db6955b6b998e529c(name, {})).resolves.toBe(null)
  })
  test("3a00d9620c2ef33412466aa18158100b", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.3a00d9620c2ef33412466aa18158100b(name, id, {})).resolves.toBe(null)
  })
  test("70253d281e06166f2d1b6a897694128e", () => {
    const id: number = 56
    return expect(instance.70253d281e06166f2d1b6a897694128e(id, {})).resolves.toBe(null)
  })
  test("d1ac8dd066753a9268189bef9e8d7516", () => {
    return expect(instance.d1ac8dd066753a9268189bef9e8d7516({})).resolves.toBe(null)
  })
})

describe("FeatureApi", () => {
  let instance: api.FeatureApi
  beforeEach(function() {
    instance = new api.FeatureApi(config)
  });

  test("0046884845bd07f1b308a84ee5c78a43", () => {
    const name: string = "name_example"
    return expect(instance.0046884845bd07f1b308a84ee5c78a43(name, {})).resolves.toBe(null)
  })
  test("9521496ff8ea68c45217ad52ca6dd01d", () => {
    return expect(instance.9521496ff8ea68c45217ad52ca6dd01d({})).resolves.toBe(null)
  })
  test("9ffd305291fd52a23ff9cd5990ef3848", () => {
    const id: number = 56
    return expect(instance.9ffd305291fd52a23ff9cd5990ef3848(id, {})).resolves.toBe(null)
  })
  test("bb5a9e8f110f4c16c1f1f0ad114a8469", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.bb5a9e8f110f4c16c1f1f0ad114a8469(name, id, {})).resolves.toBe(null)
  })
  test("d55d325b3f4a902ddddb46d59b3f43f3", () => {
    const id: number = 56
    return expect(instance.d55d325b3f4a902ddddb46d59b3f43f3(id, {})).resolves.toBe(null)
  })
})

describe("FeatureTypeApi", () => {
  let instance: api.FeatureTypeApi
  beforeEach(function() {
    instance = new api.FeatureTypeApi(config)
  });

  test("9b2c3c9068d68c1aead0b780d2a84df4", () => {
    const id: number = 56
    return expect(instance.9b2c3c9068d68c1aead0b780d2a84df4(id, {})).resolves.toBe(null)
  })
  test("b79f907f629f9a57359460592e651c83", () => {
    const name: string = "name_example"
    return expect(instance.b79f907f629f9a57359460592e651c83(name, {})).resolves.toBe(null)
  })
  test("ca224d295015eea907de4ffb54c20ec5", () => {
    return expect(instance.ca224d295015eea907de4ffb54c20ec5({})).resolves.toBe(null)
  })
  test("e0aedf41c24fab81d1267a77a1d5c4cf", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.e0aedf41c24fab81d1267a77a1d5c4cf(name, id, {})).resolves.toBe(null)
  })
  test("f7d2397b4f108ed49cf6c35919cf9774", () => {
    const id: number = 56
    return expect(instance.f7d2397b4f108ed49cf6c35919cf9774(id, {})).resolves.toBe(null)
  })
})

describe("FileApi", () => {
  let instance: api.FileApi
  beforeEach(function() {
    instance = new api.FileApi(config)
  });

  test("22fbfeda8d53a88acbdbe16ab3e86b8f", () => {
    return expect(instance.22fbfeda8d53a88acbdbe16ab3e86b8f({})).resolves.toBe(null)
  })
  test("3dc956fb0ff8265eb54d1a6d37cd98f5", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.3dc956fb0ff8265eb54d1a6d37cd98f5(name, id, {})).resolves.toBe(null)
  })
  test("b17ec9ec45bbc639e95da6411336384b", () => {
    const name: string = "name_example"
    return expect(instance.b17ec9ec45bbc639e95da6411336384b(name, {})).resolves.toBe(null)
  })
  test("d20b3d23666dc5faa14e9240433e2e86", () => {
    const id: number = 56
    return expect(instance.d20b3d23666dc5faa14e9240433e2e86(id, {})).resolves.toBe(null)
  })
  test("fb6ff65241b7d3313109e3ffa0fe0b8a", () => {
    const id: number = 56
    return expect(instance.fb6ff65241b7d3313109e3ffa0fe0b8a(id, {})).resolves.toBe(null)
  })
})

describe("GeofileApi", () => {
  let instance: api.GeofileApi
  beforeEach(function() {
    instance = new api.GeofileApi(config)
  });

  test("0141b5c135ccd51a7fafb9a7c20f71b9", () => {
    const id: number = 56
    return expect(instance.0141b5c135ccd51a7fafb9a7c20f71b9(id, {})).resolves.toBe(null)
  })
  test("25839bb1394106bf96af8dcddffa540d", () => {
    const name: string = "name_example"
    return expect(instance.25839bb1394106bf96af8dcddffa540d(name, {})).resolves.toBe(null)
  })
  test("56bd25e41f984f40623f142b39f5e827", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.56bd25e41f984f40623f142b39f5e827(name, id, {})).resolves.toBe(null)
  })
  test("5bb6226b9c5373a0798ea335b8620269", () => {
    return expect(instance.5bb6226b9c5373a0798ea335b8620269({})).resolves.toBe(null)
  })
  test("7926eea4a2535dbf125e3f0c7b01c0d5", () => {
    const id: number = 56
    return expect(instance.7926eea4a2535dbf125e3f0c7b01c0d5(id, {})).resolves.toBe(null)
  })
})

describe("GeoreferencedMapApi", () => {
  let instance: api.GeoreferencedMapApi
  beforeEach(function() {
    instance = new api.GeoreferencedMapApi(config)
  });

  test("2da30fec0600f1315a69e6b7df036264", () => {
    const id: number = 56
    return expect(instance.2da30fec0600f1315a69e6b7df036264(id, {})).resolves.toBe(null)
  })
  test("5aa6d43be787f05232b50135abc8d28a", () => {
    const id: number = 56
    return expect(instance.5aa6d43be787f05232b50135abc8d28a(id, {})).resolves.toBe(null)
  })
  test("5b7c00ad16af2bbc526833a99c0c7549", () => {
    const name: string = "name_example"
    return expect(instance.5b7c00ad16af2bbc526833a99c0c7549(name, {})).resolves.toBe(null)
  })
  test("dedf39617ecb7af96d8e8d48810b5729", () => {
    return expect(instance.dedf39617ecb7af96d8e8d48810b5729({})).resolves.toBe(null)
  })
  test("eb681b0bf23941209b4da2efc88dfb89", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.eb681b0bf23941209b4da2efc88dfb89(name, id, {})).resolves.toBe(null)
  })
})

describe("ImageApi", () => {
  let instance: api.ImageApi
  beforeEach(function() {
    instance = new api.ImageApi(config)
  });

  test("5183e00186551512bbeb06d3d6d156cd", () => {
    const id: number = 56
    return expect(instance.5183e00186551512bbeb06d3d6d156cd(id, {})).resolves.toBe(null)
  })
  test("63bb1b2694a4134e1e5798c7a683a3cc", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.63bb1b2694a4134e1e5798c7a683a3cc(name, id, {})).resolves.toBe(null)
  })
  test("8664187b703ad558537c9d91449eed7a", () => {
    return expect(instance.8664187b703ad558537c9d91449eed7a({})).resolves.toBe(null)
  })
  test("91c6b95c1b6104ea3fc0a7f1f85abafe", () => {
    const name: string = "name_example"
    return expect(instance.91c6b95c1b6104ea3fc0a7f1f85abafe(name, {})).resolves.toBe(null)
  })
  test("e76e9b25359179f7558a7309abaa8bd1", () => {
    const id: number = 56
    return expect(instance.e76e9b25359179f7558a7309abaa8bd1(id, {})).resolves.toBe(null)
  })
})

describe("LogApi", () => {
  let instance: api.LogApi
  beforeEach(function() {
    instance = new api.LogApi(config)
  });

  test("3ac95b87739c3f60f50f01405bde87ad", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.3ac95b87739c3f60f50f01405bde87ad(name, id, {})).resolves.toBe(null)
  })
  test("4aa2b06765e6a46bfee37102d6810c88", () => {
    const id: number = 56
    return expect(instance.4aa2b06765e6a46bfee37102d6810c88(id, {})).resolves.toBe(null)
  })
  test("a8600d888983a5555731f45fa9600ddb", () => {
    const id: number = 56
    return expect(instance.a8600d888983a5555731f45fa9600ddb(id, {})).resolves.toBe(null)
  })
  test("c4d265e8dccd6fd68487c2bfbe5943ac", () => {
    const name: string = "name_example"
    return expect(instance.c4d265e8dccd6fd68487c2bfbe5943ac(name, {})).resolves.toBe(null)
  })
  test("f98af73e23990227213ec217d6670d2b", () => {
    return expect(instance.f98af73e23990227213ec217d6670d2b({})).resolves.toBe(null)
  })
})

describe("MapViewApi", () => {
  let instance: api.MapViewApi
  beforeEach(function() {
    instance = new api.MapViewApi(config)
  });

  test("01375ebe2deaa8778d005ccf378ba312", () => {
    const name: string = "name_example"
    return expect(instance.01375ebe2deaa8778d005ccf378ba312(name, {})).resolves.toBe(null)
  })
  test("7781581fa54d42b16f38aa39e5ca0553", () => {
    const id: number = 56
    return expect(instance.7781581fa54d42b16f38aa39e5ca0553(id, {})).resolves.toBe(null)
  })
  test("8310101e74c64a50acdf3ab482d91216", () => {
    return expect(instance.8310101e74c64a50acdf3ab482d91216({})).resolves.toBe(null)
  })
  test("8fe83ba341aa4553dcc2c0d02158caff", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.8fe83ba341aa4553dcc2c0d02158caff(name, id, {})).resolves.toBe(null)
  })
  test("d8860be06ffbb834f065f28b4ca24063", () => {
    const id: number = 56
    return expect(instance.d8860be06ffbb834f065f28b4ca24063(id, {})).resolves.toBe(null)
  })
})

describe("PointApi", () => {
  let instance: api.PointApi
  beforeEach(function() {
    instance = new api.PointApi(config)
  });

  test("414e326e5df569e950277de2c8e9c3b1", () => {
    return expect(instance.414e326e5df569e950277de2c8e9c3b1({})).resolves.toBe(null)
  })
  test("5a5298550ce46a9468da1fc44a5851e2", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.5a5298550ce46a9468da1fc44a5851e2(name, id, {})).resolves.toBe(null)
  })
  test("7b9b6b981e45df08007c3f1a42a57595", () => {
    const name: string = "name_example"
    return expect(instance.7b9b6b981e45df08007c3f1a42a57595(name, {})).resolves.toBe(null)
  })
  test("8382eb01398d1029539a633a18910721", () => {
    const id: number = 56
    return expect(instance.8382eb01398d1029539a633a18910721(id, {})).resolves.toBe(null)
  })
  test("84890aa276d26faec598361de21ed829", () => {
    const id: number = 56
    return expect(instance.84890aa276d26faec598361de21ed829(id, {})).resolves.toBe(null)
  })
})

describe("SxgUserApi", () => {
  let instance: api.SxgUserApi
  beforeEach(function() {
    instance = new api.SxgUserApi(config)
  });

  test("1015f4f6430d718f185eca3cc2423024", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.1015f4f6430d718f185eca3cc2423024(name, id, {})).resolves.toBe(null)
  })
  test("367790b415fe7e968903353e93752d48", () => {
    const id: number = 56
    return expect(instance.367790b415fe7e968903353e93752d48(id, {})).resolves.toBe(null)
  })
  test("8fe91923e4e3c2c8daac2a888c304eeb", () => {
    const id: number = 56
    return expect(instance.8fe91923e4e3c2c8daac2a888c304eeb(id, {})).resolves.toBe(null)
  })
  test("9b39d49adef3b6e430abac14641a50fa", () => {
    return expect(instance.9b39d49adef3b6e430abac14641a50fa({})).resolves.toBe(null)
  })
  test("dbd8a6874ab9d1cab12748fcf39b8a53", () => {
    const name: string = "name_example"
    return expect(instance.dbd8a6874ab9d1cab12748fcf39b8a53(name, {})).resolves.toBe(null)
  })
})

describe("TagApi", () => {
  let instance: api.TagApi
  beforeEach(function() {
    instance = new api.TagApi(config)
  });

  test("35978f1f50ee3ef20582e565ac7b6720", () => {
    const id: number = 56
    return expect(instance.35978f1f50ee3ef20582e565ac7b6720(id, {})).resolves.toBe(null)
  })
  test("3e3cc7bb590b34997dd14f6ca40743f3", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.3e3cc7bb590b34997dd14f6ca40743f3(name, id, {})).resolves.toBe(null)
  })
  test("57fc6cc7a88ad83c6888887c40e6094a", () => {
    return expect(instance.57fc6cc7a88ad83c6888887c40e6094a({})).resolves.toBe(null)
  })
  test("5ac3d7ca53caad3cfe1e4ef1a673ba07", () => {
    const id: number = 56
    return expect(instance.5ac3d7ca53caad3cfe1e4ef1a673ba07(id, {})).resolves.toBe(null)
  })
  test("c851a6840f9037781df6fcc88bd294e4", () => {
    const name: string = "name_example"
    return expect(instance.c851a6840f9037781df6fcc88bd294e4(name, {})).resolves.toBe(null)
  })
})

describe("TeamMemberApi", () => {
  let instance: api.TeamMemberApi
  beforeEach(function() {
    instance = new api.TeamMemberApi(config)
  });

  test("504f1e2454344367b03491dac070cd56", () => {
    const id: number = 56
    return expect(instance.504f1e2454344367b03491dac070cd56(id, {})).resolves.toBe(null)
  })
  test("50e42d2216f357cb3fc2c9d04e56d568", () => {
    return expect(instance.50e42d2216f357cb3fc2c9d04e56d568({})).resolves.toBe(null)
  })
  test("793a2f9812ee40dbbf2e79904985274c", () => {
    const name: string = "name_example"
    return expect(instance.793a2f9812ee40dbbf2e79904985274c(name, {})).resolves.toBe(null)
  })
  test("87f4ab442a55d282e1ebade1a87da9c3", () => {
    const id: number = 56
    return expect(instance.87f4ab442a55d282e1ebade1a87da9c3(id, {})).resolves.toBe(null)
  })
  test("d17af343b44e4ce310e0f9288ec00d3a", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.d17af343b44e4ce310e0f9288ec00d3a(name, id, {})).resolves.toBe(null)
  })
})

describe("TripLogsApi", () => {
  let instance: api.TripLogsApi
  beforeEach(function() {
    instance = new api.TripLogsApi(config)
  });

  test("2458cebcb928d0cf634acaf03b114ba0", () => {
    const id: number = 56
    return expect(instance.2458cebcb928d0cf634acaf03b114ba0(id, {})).resolves.toBe(null)
  })
  test("3b7d4d912acf1978ce1f451c27525b85", () => {
    const name: string = "name_example"
    return expect(instance.3b7d4d912acf1978ce1f451c27525b85(name, {})).resolves.toBe(null)
  })
  test("a395e23edaa4ccfce651904bf97ff304", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.a395e23edaa4ccfce651904bf97ff304(name, id, {})).resolves.toBe(null)
  })
  test("b0be1724d2b4030ef83d5fe144802562", () => {
    const id: number = 56
    return expect(instance.b0be1724d2b4030ef83d5fe144802562(id, {})).resolves.toBe(null)
  })
  test("c15a7f9a6008ff7e48676ca3cf804d45", () => {
    return expect(instance.c15a7f9a6008ff7e48676ca3cf804d45({})).resolves.toBe(null)
  })
})

describe("UserApi", () => {
  let instance: api.UserApi
  beforeEach(function() {
    instance = new api.UserApi(config)
  });

  test("1df092f5eddb2e29c3c5aa8043dd6d44", () => {
    return expect(instance.1df092f5eddb2e29c3c5aa8043dd6d44({})).resolves.toBe(null)
  })
  test("3465c05467f56755d8fde6dfe336f784", () => {
    const name: string = "name_example"
    return expect(instance.3465c05467f56755d8fde6dfe336f784(name, {})).resolves.toBe(null)
  })
  test("acefdff5c10ad10456b5e12506f8ab63", () => {
    const name: string = "name_example"
    const id: number = 56
    return expect(instance.acefdff5c10ad10456b5e12506f8ab63(name, id, {})).resolves.toBe(null)
  })
  test("b3671c968c691df9358298f3a285c767", () => {
    const id: number = 56
    return expect(instance.b3671c968c691df9358298f3a285c767(id, {})).resolves.toBe(null)
  })
  test("ca775ff26d0144e4b01abbd8c926f7c3", () => {
    const id: number = 56
    return expect(instance.ca775ff26d0144e4b01abbd8c926f7c3(id, {})).resolves.toBe(null)
  })
})

