<?php
// This file generated by Propel 1.7.2-dev convert-conf target
// from XML runtime conf file D:\wamp\www\speogis\db\propel_1_6_pr\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'speogis' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=indmarke_wp733',
        'user' => 'indmarke_wp733',
        'password' => '%!SXe8.rxg~v',
      ),
    ),
    'default' => 'speogis',
  ),
  'generator_version' => '1.7.2-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-speogis-conf.php');
return $conf;